services:
  - type: web
    name: lu-estilo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lu-estilo-db
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: SENTRY_DSN
        sync: false

databases:
  - name: lu-estilo-db
    databaseName: lu_estilo
    user: postgres
    plan: free 