"""initial migration

Revision ID: ed005b962572
Revises: 
Create Date: 2025-05-26 13:31:47.373587

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "ed005b962572"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
